### ISSUE TITLE
scrub is cancelled immediately

### ISSUE THREAD

**Issue by fallenguru** [lnicola/systemd-zpool-scrub#1]
The service unit does not work at all, as systemd will execute ExecStart (which returns immediately), think it's done and run ExecStop. Thus the scrub always gets cancelled right after it's started.

Debian 8.3 jessie (systemd 215-17+deb8u3, ZFS on Linux 0.6.5.2-2)

**Comment by lnicola** [comment]
That's right, sorry for that. I was using the fixed version, but I forgot to commit it here.

I wasn't able to make this work nicely with systemd.

**Comment by fallenguru** [comment]
I think I've figured it out. If you use RemainAfterExit=yes ExecStop will not be called immediately. The only disadvantage is that the scrub will be considered running indefinitely (until it's explicitly stopped).

**Comment by lnicola** [comment]
Which is arguably worse. That's actually the first thing I tried.
